apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs-server.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
    - name: mountd
      port: 20048
      protocol: TCP
      targetPort: 20048
    - name: rpcbind
      port: 111
      protocol: TCP
      targetPort: 111
  selector:
    {{- include "nfs-server.selectorLabels" . | nindent 4 }}
