#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: rancher
#  namespace: default
#  annotations:
#    kubernetes.io/ingress.allow-http: "false"
#spec:
#  rules:
#    - host: rancher.kumuruku.com
#      http:
#        paths:
#        - backend:
#            service:
#              name: rancher-np
#              port: 80
#          path: /
#          pathType: Prefix
#  tls:
#  - hosts:
#    - rancher.kumuruku.com
#    secretName: rancher-kumuruku-com-tls