apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}