apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    minecraft-minecraft
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: minecraft-minecraft-svc
#    traefik.ingress.kubernetes.io/affinity: "true"
#    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  {{ .Values.minecraftService.ip }}
  ports:
    # pihole use Ports to expose (53, 80, 67, 443), the bare minimum ports required for Pi-holes HTTP and DNS services
    - port: 25565
      targetPort: 25565
      name: port25565
      protocol: TCP
    - port: 19132
      targetPort: 19132
      name: port19132
      protocol: UDP
  selector:
    app: minecraft-minecraft
  type: LoadBalancer