apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: minecraft-minecraft-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  {{ .Values.minecraftService.ip }}
  ports:
    - port: 25565
      targetPort: 25565
      name: port25565
      protocol: TCP
    - port: 19132
      targetPort: 19132
      name: port19132
      protocol: UDP
  selector:
    app: minecraft-minecraft
  type: LoadBalancer