apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 31111
      nodePort: 31111
      targetPort: 80
      name: web
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
#   app: {{ include "nginx.fullname" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: nginx-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  {{ .Values.service.ip }}
  ports:
    - port: 80
      targetPort: 80
      name: port80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: port443
      protocol: TCP
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
  type: LoadBalancer