apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort.port }}
      name: web
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
#   app: {{ include "nginx.fullname" . }}
