apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
  labels:
    {{- include "minecraft-config.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: minecraft-minecraft
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  192.168.0.211
  ports:
    - port: 60211
      targetPort: 25565
      name: port60211
      protocol: TCP
  selector:
    app: minecraft-minecraft
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mc-games-lb
  labels:
    {{- include "minecraft-config.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: mc-games-minecraft
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  192.168.0.212
  ports:
    - port: 60212
      targetPort: 25565
      name: port60212
      protocol: TCP
  selector:
    app: mc-games-minecraft
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mc-origins-lb
  labels:
    {{- include "minecraft-config.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: mc-origins-minecraft
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  192.168.0.213
  ports:
    - port: 60213
      targetPort: 25565
      name: port60213
      protocol: TCP
  selector:
    app: mc-origins-minecraft
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mc-pvp-lb
  labels:
    {{- include "minecraft-config.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: mc-pvp-minecraft
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  192.168.0.214
  ports:
    - port: 60214
      targetPort: 25565
      name: port60214
      protocol: TCP
  selector:
    app: mc-pvp-minecraft
  type: LoadBalancer