apiVersion: v1
kind: Service
metadata:
  name: minecraft
  labels:
    {{- include "minecraft-config.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: minecraft-minecraft
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  192.168.0.211
  ports:
    - port: 60211
      targetPort: 25565
      name: port25565
      protocol: TCP
  selector:
    app: minecraft-minecraft
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mc-games
  labels:
    {{- include "minecraft-config.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: mc-games-minecraft
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  192.168.0.212
  ports:
    - port: 60212
      targetPort: 25565
      name: port25566
      protocol: TCP
  selector:
    app: mc-games-minecraft
  type: LoadBalancer