apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-cows
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: rancher-cows
  template:
    metadata:
      labels:
        app: rancher-cows
    spec:
      containers:
        - name: rancher-cows
          image: bashofmann/rancher-demo:1.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: web
            protocol: TCP
          env:
            - name: COW_COLOR
              value: purple
          readinessProbe:
            httpGet:
              port: web
              path: /
