apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-cows.fullname" . }}
  labels:
    {{- include "rancher-cows.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceClusterIP.type }}
  ports:
    - port: {{ .Values.serviceClusterIP.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rancher-cows.selectorLabels" . | nindent 4 }}
