apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-cows.fullname" . }}-np
  labels:
    {{- include "rancher-cows.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containerPort.port }}
      nodePort: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort.port }}
      protocol: TCP
      name: http
  selector:
    #app: {{ include "rancher-cows.fullname" . }}
    {{- include "rancher-cows.selectorLabels" . | nindent 4 }}

