apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: {{ include "metallb-config.fullname" . }}
  labels:
  {{- include "metallb-config.labels" . | nindent 4 }}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      {{- .Values.config.ipPool }}