apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
    WEBPASSWORD: wordpress
    TZ: 'Europe/Copenhagen'
    DNS1: 8.8.8.8
    DNS2: 1.1.1.1