apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress
  namespace: wordpress
spec:
  rules:
    - host: wordpress.10.0.100.200.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: wordpress
              servicePort: 80