apiVersion: v1
kind: Secret
metadata:
  name: mariadb-pass
  namespace: wordpress
  labels:
    app: wordpress
data:
  # This value is base64-encoded. Do not use this password in production!
  password: WKpPmc48Z2dRWfmaNFSWAz6E7yqd8T