apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: wordpress-mariadb
    port: 3306
    targetPort: 3306
  selector:
    app: wordpress
    tier: mariadb
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-np
  namespace: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: web
    nodePort: 31120
    port: 31120
    targetPort: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort