apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
data:
    WEBPASSWORD: pihole
    TZ: 'Europe/Copenhagen'
    DNS1: 8.8.8.8
    DNS2: 1.1.1.1