apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: default
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: pihole.kumuruku.com
      http:
        paths:
        - backend:
            service:
              name: pihole
              port: 
                number: 80
          path: /
          pathType: Prefix
  tls:
  - hosts:
    - pihole.kumuruku.com
    secretName: pihole-kumuruku-com-tls