apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.namePiHole }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
#      storage: {{ .Values.pv.capacityPiHole }}
  storageClassName: nfs-client

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.nameDnsmasq }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
#      storage: {{ ".Values.pv.capacityDnsmasq" }}
  storageClassName: nfs-client
