apiVersion: v1
kind: Secret
metadata:
    name: {{ include "pihole.fullname" . }}
type: Opaque
data:
  {{- if .Values.adminPassword }}
  password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}