apiVersion: v1
kind: Secret
metadata:
    name: {{ include "pihole.fullname" . }}
type: Opaque
data:
  {{- if .Values.adminPassword }}
  WEBPASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  WEBPASSWORD: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}