apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  externalTrafficPolicy: Local
  loadBalancerIP:  {{ .Values.service.ip }}
  ports:
    # pihole use Ports to expose (53, 80, 67, 443), the bare minimum ports required for Pi-holes HTTP and DNS services
    - port: 80
      targetPort: 80
      name: port80
      protocol: TCP
    - port: 443
      targetPort: 443
      name: port443
      protocol: TCP
    - port: 53
      targetPort: 53
      protocol: TCP
      name: port53
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: {{ .Values.service.ip }}
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: port53-udp
    - port: 67
      targetPort: 67
      protocol: UDP
      name: port67-udp
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  type: LoadBalancer